language: nix

sudo: true

git:
  depth: 1

env:
  global:
  matrix:
    - GHCVERSION=ghc844
    - GHCVERSION=ghc865
    - GHCVERSION=ghc882
    - GHCVERSION=ghc8101

matrix:
  allow_failures:
  exclude:

script:
  - nix-build --argstr compiler $GHCVERSION

branches:
  only:
    - master
